PATH=$PATH:~/.cabal/bin

# export JAVA_OPTS="-d64"
export JRUBY_OPTS="--1.9 -X+O"

HISTSIZE=5000
HISTFILESIZE=5000

export JAVA_HOME='/usr/lib/jvm/java-6-openjdk-amd64'
export GRAILS_HOME=/opt/grails/grails-1.3.7
export GROOVY_HOME=/opt/groovy/groovy-1.8.7

PATH=$PATH:/usr/bin/vendor_perl:~/hadoop-1.0.3/bin/:/home/g/reader-server/node_modules/.bin

export PATH=$JAVA_HOME/bin:$GRAILS_HOME/bin:$GROOVY_HOME/bin:$PATH
export ES_HOME=/home/g/es
